//! macOS backend: global event tap via objc2 (CGEventTap, ListenOnly).
//!
//! - CGEvent::tap_create(SessionEventTap, HeadInsertEventTap, ListenOnly, mask, cb, null)
//! - CGEventType::KeyDown -> InputEvent::Key(keycode) ONLY (no KeyUp double-play)
//! - LeftMouseDown/RightMouseDown/OtherMouseDown -> InputEvent::Mouse(..)
//! - no CGEventTapCreateRunLoopSource: use CFMachPortCreateRunLoopSource + CFRunLoopRun
//! - None from tap_create = permission denied -> BackendError::Permission

#[cfg(not(target_os = "macos"))]
use futures::stream::BoxStream;

#[cfg(not(target_os = "macos"))]
use crate::backend::{BackendError, InputBackend};

/// The macOS input backend.
///
/// `enable_trackpads` is kept for API parity with the other backends; on macOS
/// the CGEventTap layer does not distinguish a trackpad tap from a mouse click,
/// so the field is currently unused.
#[allow(dead_code)]
pub struct MacosBackend {
    enable_trackpads: bool,
}

#[allow(dead_code)]
impl MacosBackend {
    pub fn new(enable_trackpads: bool) -> MacosBackend {
        MacosBackend { enable_trackpads }
    }
}

#[cfg(target_os = "macos")]
mod imp {
    use std::ffi::c_void;
    use std::sync::Mutex;
    use std::sync::mpsc as std_mpsc;
    use std::time::Duration;

    use futures::stream::BoxStream;
    use tokio::sync::mpsc;
    use tokio_stream::wrappers::ReceiverStream;

    use objc2_core_foundation::{CFMachPortCreateRunLoopSource, CFRunLoop, kCFRunLoopDefaultMode};
    use objc2_core_graphics::{
        CGEvent, CGEventField, CGEventMask, CGEventTapLocation, CGEventTapOptions,
        CGEventTapPlacement, CGEventTapProxy, CGEventType,
    };

    use crate::backend::{
        BackendError, CHANNEL_CAP, GuardedSenderStream, InputBackend, MacosBackend, emit,
        try_start_sender,
    };
    use crate::domain::{InputEvent, MouseButton};

    /// `CGEventMaskBit` is a C macro not generated by objc2, so build the mask
    /// by hand: bit `n` of the mask corresponds to event type `n`.
    fn mask_bit(ty: CGEventType) -> CGEventMask {
        1u64 << (ty.0 as u64)
    }

    /// Map a CGEvent to our normalized `InputEvent`, or `None` if we don't care.
    unsafe fn map_event(event_type: CGEventType, event: *const CGEvent) -> Option<InputEvent> {
        let ev = &*event;
        // `CGEventType` is a `#[repr(transparent)]` struct of associated consts,
        // not an enum, so match on the raw `u32` rather than the const patterns.
        if event_type == CGEventType::KeyDown {
            let code = CGEvent::integer_value_field(Some(ev), CGEventField::KeyboardEventKeycode);
            Some(InputEvent::Key(code as u16))
        } else if event_type == CGEventType::LeftMouseDown {
            Some(InputEvent::Mouse(MouseButton::Left))
        } else if event_type == CGEventType::RightMouseDown {
            Some(InputEvent::Mouse(MouseButton::Right))
        } else if event_type == CGEventType::OtherMouseDown {
            let n = CGEvent::integer_value_field(Some(ev), CGEventField::MouseEventButtonNumber);
            let button = match n {
                0 => MouseButton::Left,
                1 => MouseButton::Right,
                2 => MouseButton::Middle,
                3 => MouseButton::Back,
                4 => MouseButton::Forward,
                other => MouseButton::Other(other as u16),
            };
            Some(InputEvent::Mouse(button))
        } else {
            None
        }
    }

    /// CGEventTap callback (ListenOnly): forward the event and return it unchanged.
    extern "C" fn tap_callback(
        _proxy: CGEventTapProxy,
        event_type: CGEventType,
        event: *const CGEvent,
        _user_info: *mut c_void,
    ) -> *const CGEvent {
        unsafe {
            if let Some(input) = map_event(event_type, event) {
                emit(input);
            }
        }
        event
    }

    fn event_mask() -> CGEventMask {
        mask_bit(CGEventType::KeyDown)
            | mask_bit(CGEventType::LeftMouseDown)
            | mask_bit(CGEventType::RightMouseDown)
            | mask_bit(CGEventType::OtherMouseDown)
    }

    /// Create the tap on the run-loop thread, then block in the run loop for the
    /// process lifetime. Reports creation success/failure back over `ready`.
    fn run_tap(ready: std_mpsc::Sender<Result<(), BackendError>>) {
        unsafe {
            let mach_port = CGEvent::tap_create(
                CGEventTapLocation::SessionEventTap,
                CGEventTapPlacement::HeadInsertEventTap,
                CGEventTapOptions::ListenOnly,
                event_mask(),
                Some(tap_callback),
                std::ptr::null_mut(),
            );

            let mach_port = match mach_port {
                Some(p) => p,
                None => {
                    let _ = ready.send(Err(BackendError::Permission));
                    return;
                }
            };

            let source = CFMachPortCreateRunLoopSource(None, Some(&mach_port), 0);
            let run_loop = CFRunLoop::current();
            if let (Some(rl), Some(src)) = (run_loop.as_deref(), source.as_deref()) {
                rl.add_source(Some(src), kCFRunLoopDefaultMode);
            }
            CGEvent::tap_enable(&mach_port, true);

            let _ = ready.send(Ok(()));

            // Blocks for the process lifetime; the stream ends when the sender drops.
            CFRunLoop::run();
        }
    }

    impl InputBackend for MacosBackend {
        fn events(&mut self) -> Result<BoxStream<'static, InputEvent>, BackendError> {
            let (tx, rx) = mpsc::channel::<InputEvent>(CHANNEL_CAP);
            try_start_sender(tx)?;

            let (ready_tx, ready_rx) = std_mpsc::channel::<Result<(), BackendError>>();

            std::thread::Builder::new()
                .name("wayclick-cgeventtap".into())
                .spawn(move || run_tap(ready_tx))
                .map_err(|e| BackendError::Start(format!("failed to spawn tap thread: {e}")))?;

            match ready_rx.recv_timeout(Duration::from_secs(5)) {
                Ok(Ok(())) => {
                    tracing::info!("macOS CGEventTap started");
                    Ok(GuardedSenderStream::new(ReceiverStream::new(rx)).boxed())
                }
                Ok(Err(e)) => Err(e),
                Err(_) => Err(BackendError::Start(
                    "timed out waiting for CGEventTap to start".into(),
                )),
            }
        }

        fn name(&self) -> &'static str {
            "macos-cgeventtap"
        }
    }
}

#[cfg(not(target_os = "macos"))]
impl InputBackend for MacosBackend {
    fn events(&mut self) -> Result<BoxStream<'static, crate::domain::InputEvent>, BackendError> {
        Err(BackendError::Start("macos-only".into()))
    }

    fn name(&self) -> &'static str {
        "macos-cgeventtap"
    }
}
